### ISSUE TITLE
Visible delay between app UI and web view when switching reading modes

### ISSUE THREAD

**Issue by JayPanoz** [readium/r2-testapp-swift#213] opened 2018-10-04 13:07 UTC
Version is `alpha-1.0.5` on iOS 11.4.3.

This appears to be a regression as it didn’t occur before. I can’t tell when it first appeared though. 

When changing reading modes, there is quite a visible delay between the app UI and the web view. Background-color change for the app UI is instantaneous but the web view is lagging.

![bug](https://user-images.githubusercontent.com/12599652/46475793-cbc6a980-c7e6-11e8-9e8f-a9f77ec217b6.gif)

That happened to be one main concern when dealing with the first implementation with Alexandre but everything went smoothly – there wasn’t such a discoordination between those components. So maybe that regression was introduced during a refacto?

**Comment by gbugniot** [comment] 2018-10-18 09:09
At first glance, this might be related to the new user settings injection implementation.

**Comment by mickael-menu** [comment] 2019-10-25 15:34
I'm closing this issue as it is quite old and I couldn't reproduce it on the simulator nor my devices. Feel free to reopen if needed.

There is a slight delay but it's far from being like in Jiminy's GIF, and it's to be expected since the theme application is asynchronous. I think the API could benefit from a completion closure called when the theme is applied in the navigator, so that the app can update its own interface afterwards. But it's probably not worth adding that now since a refactoring of the user settings is coming once the public API will be specified.

**Closed by mickael-menu** 2019-10-25 15:34 UTC
