### ISSUE TITLE
Add page margins to user settings

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-swift#87] opened 2018-04-29 01:25 UTC
we need to move page margin into main settings if those are not publisher dependent.

**Comment by JayPanoz** [comment] 2018-04-29 10:38
So yeah I can confirm they are totally publisher-independent, since we override publishers’ `margin` and `padding` for both [the `html` element](https://github.com/readium/readium-css/blob/47718fbe57a12a523b2027b976e76317f3650717/css/src/modules/ReadiumCSS-pagination.css#L62) and [the `body` element](https://github.com/readium/readium-css/blob/master/css/src/modules/ReadiumCSS-pagination.css#L94), and define our own (especially `padding` instead of using `column-gap` [through the CSS `--RS__pageGutter` variable](https://github.com/readium/readium-css/blob/master/css/src/modules/ReadiumCSS-pagination.css#L30)).

That being said, [it is currently categorized as “Chrome Advanced”](https://github.com/readium/readium-css/blob/master/docs/CSS11-overrides_classification.md#chrome-advanced) so the settings listed are advanced in some way, but not publishers-dependent (contrary to `text-align` for instance, which requires the “advanced setting flag”). So we have other advanced settings (esp. number of columns) behaving as page margin. As stated is the doc, “this classification might change and additional items be added in the future” because it kinda was [an artificial one at the time it was created](https://github.com/readium/readium-css/issues/16).

This is probably something we can discuss during the next call, UX-wise. It made a lot of sense when designing the user settings (selectors, declaration, `!important`, etc.) but it should also work for implementers, and maybe we can either refine it, or provide stronger guidance UX-wise e.g. “This can be in the main panel of user settings or the advanced one”, “this is not meant to be in the main panel”, etc.).

**Comment by JayPanoz** [comment] 2018-05-04 15:28
Out of curiosity, I took a quick look at the elephant in the room, who doesn’t have advanced settings *per se* but offer users page margin and columns settings. 

I think it would not be unexpected to find those ones in the main panel, after the usual user settings (font-size, font-family, reading modes…).

![screenshot_20180504-171033](https://user-images.githubusercontent.com/12599652/39636387-51231f9a-4fc0-11e8-857e-6edd64cafa57.png)

![screenshot_20180504-171040](https://user-images.githubusercontent.com/12599652/39636390-53ca2e82-4fc0-11e8-9df7-a3f68d41c55d.png)

![screenshot_20180504-171115](https://user-images.githubusercontent.com/12599652/39636395-56bf2764-4fc0-11e8-943a-67c9e5fdbb06.png)

![screenshot_20180504-171122](https://user-images.githubusercontent.com/12599652/39636398-5972123c-4fc0-11e8-8399-d28669010da8.png)

Note the columns setting is only displayed in landscape, which is something we should do as well.

![photo 04-05-2018 17 16 44](https://user-images.githubusercontent.com/12599652/39636427-6e98e258-4fc0-11e8-9970-6cf4921a58ae.png)

That can at least serve as food for thought.

**Comment by HadrienGardeur** [comment] 2018-06-13 16:33
I'm not sure why this is in the Epic for the new approach to user settings (#67).

**Comment by mickael-menu** [comment] 2021-02-08 15:28
I agree with @JayPanoz that page margins (and also columns which don't require publisher's styles off) are a good fit for the advanced settings panel.

But maybe there's a case for renaming `--USER__advancedSettings` into `--USER__publisherStyles` in Readium CSS.

I'm closing this issue but feel free to reopen if there was no clear consensus.

**Closed by mickael-menu** 2021-02-08 15:28 UTC
