### ISSUE TITLE
LCP: open from Files does not work anymore

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#263] opened 2019-05-17 03:22 UTC
One cannot anymore import a license in the app by selecting it in the Files app and Share with R2 Reader.

**Comment by llemeurfr** [comment] 2019-05-17 03:24
The message is of type: <file> couldn't be moved because you don't have permission to access "Documents".

**Comment by llemeurfr** [comment] 2019-10-07 15:25
I still see this issue with a license generated from my local server and shared on iCloud.
The message is: Error while importing the publication: The file "xxxx.lcpl" couldn't be opened because there is no such file.

The same license is correctly handled if I import the license from the "+" button inside the app. 
Funny think is that if I do the same with a license corresponding to content in a remote server (e.g. the front-prod sandbox server) I have no problem importing the publication via File / share.

**Comment by mickael-menu** [comment] 2019-10-22 12:27
I believe this is actually a bug in the Files app. Basically what's happening is that Files sends the local path to our app regardless of whether the file is downloaded or not (small cloud icon overlay). So if the file we try to open is not already on the device, our app can't read it.

I did find a workaround, by setting `LSSupportsOpeningDocumentsInPlace` to `NO` in the `Info.plist` of the app. This forces Files to first download the file, and then copy it in our app's sandbox. However to do that I had to remove `UISupportsDocumentBrowser=YES`, because it implicitely sets `LSSupportsOpeningDocumentsInPlace` to `YES`. Since we are not using `UIDocumentBrowserViewController` in the app, it's probably fine.

On a side note, after upgrading to iOS 13 to check if the issue was fixed in Files, Readium was not recognized for LCPL files anymore from the Files app. Adding a new Document Type in the app with exactly the same parameters but a different extension worked as intended. I can't explain it and didn't find a way to reset the shared Document Types so far.

**Closed** 2019-11-19 20:07 UTC
Labels: bug

**Comment by llemeurfr** [comment] 2019-11-20 08:43
Does closing means that lcpl files are now recognized again in Files?

**Comment by aferditamuriqi** [comment] 2019-11-20 09:55
@llemeurfr the issue was tagged to the PR, so this would mean it should work now again, i haven't gotten a chance to test all scenarios, but a new testflight is on its way
